### ISSUE TITLE
Multi-Node: Trainer Stuck on step 0

### ISSUE THREAD

**Issue by Danau5tin** [PrimeIntellect-ai/prime-rl#1057]
Hello 👋

## Trainer output
```
11:03:58    INFO Initializing model and tokenizer (name='willcb/Qwen3-32B' attn='flash_attention_2' compile=None ac=ActivationCheckpointConfig(freq=1) reshard_after_forward=True trust_remote_code=True dp_replicate=1 ep=1 tp=1 cp=1 impl='hf' log_signature=False load_using_meta=False optimization_dtype='float32' reduce_dtype='float32' moe_use_grouped_mm=True debug=DebugModelConfig(num_layers=None, random_init=False))
Loading checkpoint shards: 100%|███████████████████████████████████████████| 14/14 [01:19<00:00,  5.69s/it]
11:05:18    INFO Applied activation checkpointing (freq=1)
11:05:18    INFO Building 1-D device mesh with ['dp_shard'], [8]
11:07:08    INFO model num_layers: 64
11:07:08    INFO Initializing optimizer (lr=1e-06 weight_decay=0.01 max_norm=1.0 type='adamw' betas1=0.9 betas2=0.999)
11:07:08    INFO Using `grpo` loss (norm_type='token' type='grpo' clip_ratio=8.0)
11:07:08    INFO Using `constant` scheduler (type='constant')
11:07:08    INFO Initializing weight checkpoint manager (interval=None save_async=True)
11:07:08    INFO Initializing checkpoint manager (interval=20 resume_step=None keep=None skip_dataloader=False)
11:07:08    INFO Starting from step 0 (total_tokens=0, total_samples=0)
11:07:08    INFO Initializing data loader (fake=None)
11:07:08    INFO Starting training loop (config.max_steps=None)
11:07:08    INFO Starting training step 0
11:07:08    INFO Waiting for training batch to arrive
11:07:08    INFO Starting forward and backward pass (num_micro_batches=1)
```

The above is the output of the trainer. It hangs here seemingly forever, and all trainer GPUs stay at 0% usage whilst this shows (waited over 20 mins but no GPU usage at all registered).

I have tried on both `willcb/Qwen3-32B` & `willcb/Qwen3-14B` and it has the same effect.

## Commands I use

**On Node 1**
```bash
tmux new -s inf

# In session now
CUDA_VISIBLE_DEVICES=4,5,6,7 uv run inference @ ../infer.toml \
    --api-key $INFERENCE_SERVER_API_KEY
```

**On Node 0**
```bash
tmux new -s train
# cbtrl+b + " (for new pane)

# In bottom pane
uv run orchestrator @ ../orch.toml \
    --client.base-url http://$INFERENCE_SERVER_IP:8000/v1 \
    --client.api-key-var $INFERENCE_SERVER_API_KEY \
    --output-dir $OUTPUT_DIR

# In top pane
uv run torchrun \
    --nproc-per-node 8 \
    --local-ranks-filter 0 \
    src/prime_rl/trainer/rl/train.py @ ../train.toml \
    --output-dir $OUTPUT_DIR
```

## Configs
**infer**
```toml
[model]
name = "willcb/Qwen3-14B"

[parallel]
tp = 4
```

**orch**
```toml
batch_size = 2
micro_batch_size = 1
rollouts_per_example = 2
seq_len = 16000
mask_truncated_completions = false

[environment]
id = "my-env"

[sampling]
max_tokens = 2000
temperature = 0.9

[model]
name = "willcb/Qwen3-14B"

[wandb]
project = "my-proj"

[wandb.log_extras]
interval = 1

[ckpt]
interval = 20
```

**train**
```toml
recompute_logprobs = false

[wandb]
project = "my-proj"

[wandb.log_extras]
interval = 1

[model]
name = "willcb/Qwen3-14B"
trust_remote_code = true

[model.ac]

[optim]
lr = 1e-6

[ckpt]
interval = 20
```

## Notes
- I am confident that the nodes share a common filesystem that both nodes can read & write too
- I am also confident that NCCL & GLOO are both working between nodes (tested)
- The Orchestrator & Inference seem to be working just fine, it is the trainer which is stuck

I have followed [these](https://github.com/PrimeIntellect-ai/prime-rl/blob/main/docs/deployment.md#multi-node-training) documented instructions.

Thank you!

**Comment by Danau5tin** [comment]
I believe I fixed this by adding the below to `orch.toml`
```toml
num_train_workers = 8
```

Leaving issue open as the docs could likely do with being updated!
Thank you guys

**Comment by mikasenghaas** [comment]
yea, this is a somewhat annoying side-affecting of pre-sharding the data so that each trainer rank only consume its dp shard. it's automatically set for single node exps in `rl.py` but has to be manually set when running the orchestrator separate in multi-node. agree that we can be clearer in docs with this!

**Comment by mikasenghaas** [comment]
Closing in favor of #1061
